export const FORMAT_MAPLIST = 1;
export const FORMAT_MAPLIST_ALL_VER = 2;
export const FORMAT_NOSTALGIA_PACK = 11;
export const FORMAT_EXPERT_LIST = 51;
export const FORMAT_BEST_OF_THE_BEST = 52;

export const FORMATS_WITHOUT_GERALDO = [FORMAT_NOSTALGIA_PACK, FORMAT_BEST_OF_THE_BEST];
